"""
revenue_forecast.py
--------------------
Sections 11-15 of the automation spec: popularity/volume indexing,
demand-multiplier chain, 6/Next6/Next9-month revenue projection, and
lunch/dinner/weekday/weekend occasion splits.

PROVENANCE, STATED PLAINLY
---------------------------
The reference workbook (Memphis_38114_Menu_Creation_Updated_v11.xlsx) that
this module reproduces was hand-authored by a prior analysis pass, not
generated by any script -- confirmed from that workbook's own methodology
notes. Most of the formula chain below was reverse-verified against that
workbook's real numbers to 4+ decimal places (Category Volume Index,
Category Multiplier buckets, Market Demand Composite Index, Base Projected
Units, and the 5.4/6/9 period factors all reproduce the reference numbers
exactly). Two pieces could NOT be reverse-verified because the reference
workbook's own values for them don't fit any single consistent formula
(confirmed: Base Units does not vary monotonically with tier share, which
any capture-rate x tier-% formula would require) -- those are implemented
here as a single, transparent, ZCTA-independent POLICY instead:

  1. Base Units (Monthly): sourced from the optional comparable-restaurant
     file's real annual_qty when available (this project's actual
     decision, overriding the capture-rate-only formula this module
     originally proposed) -- see compute_base_units_monthly(). Falls back
     to a labeled capture-rate estimate only when no matched comparable
     has usable quantity data.
  2. Lunch/Dinner and Weekday/Weekend unit splits: implemented from the
     exact tier-based share table and day-count constants the reference
     workbook's own notes document as "documented judgment call" --
     these were never claimed to be measured data in the reference
     workbook either.
"""

import math

from creation_engine import ZctaContext

# ---------------------------------------------------------------------------
# 0. BEST-COMPARABLE-ITEM MATCHING
# For each generated item, search the comparable file's individual menu
# items (not restaurant-level aggregates) for items in the same category,
# rank them by a composite of sales performance and price competitiveness,
# and return the single best match. Its real price/qty become the primary
# evidence for that item's Base Units -- never an arbitrary assumption when
# a valid comparable exists.
# ---------------------------------------------------------------------------

def _category_matches(item_category_text: str, target_category: str) -> bool:
    """target_category: a creation_engine.CATEGORY_KEYWORDS label (e.g.
    'Burgers'). item_category_text: raw category text from the comparable
    file's own column (e.g. FAMILY_GROUP_NAME) -- in real MICROS-style POS
    exports this is a COARSE bucket (BURGER, ENTREE, SAND / WRAP, etc), a
    completely different taxonomy from creation_engine.CATEGORY_KEYWORDS'
    cuisine-style labels (Burgers, BBQ, Sandwiches, ...). Keyword-substring
    matching against CATEGORY_KEYWORDS was comparing across two unrelated
    vocabularies and silently failed for any target_category whose keyword
    doesn't happen to appear verbatim in a FAMILY_GROUP_NAME string (BBQ,
    Sandwiches, Mexican, etc all failed this way). Fixed: reuse the same
    CATEGORY_TO_VOLUME_BENCHMARK_KEY crosswalk already used for the
    Category Volume Index, so both features agree on which POS bucket a
    given creation_engine category maps to."""
    mapped_bucket = CATEGORY_TO_VOLUME_BENCHMARK_KEY.get(target_category)
    text = str(item_category_text).strip().upper()
    if mapped_bucket:
        return text == mapped_bucket
    # No crosswalk entry (category not in the FC-benchmark table) -- fall
    # back to keyword-substring matching against the raw text.
    from creation_engine import CATEGORY_KEYWORDS
    kws = CATEGORY_KEYWORDS.get(target_category, [target_category.lower()])
    return any(kw in text.lower() for kw in kws)


def find_best_comparable_item(target_category: str, target_price: float,
                               comparable_items_df, price_weight: float = 0.5,
                               volume_weight: float = 0.5):
    """comparable_items_df: the normalized comparable dataframe (from
    input_normalizer.normalize_comparable_restaurant_dataframe), with
    item_name/item_category/price/annual_qty columns -- item-level rows,
    not restaurant-aggregated.

    Composite score per candidate item:
      price_score  = 1 - min(1, abs(item_price - target_price) / target_price)
      volume_score = item_qty / max_qty_among_candidates
      composite    = price_weight * price_score + volume_weight * volume_score

    Returns a dict {name, category, price, annual_qty, composite_score,
    match_note} for the single highest-scoring candidate, or None if no
    candidate with both a category match and usable price+qty exists.
    """
    import pandas as pd

    if comparable_items_df is None or comparable_items_df.empty:
        return None
    if 'item_category' not in comparable_items_df.columns or 'item_name' not in comparable_items_df.columns:
        return None

    candidates = comparable_items_df[
        comparable_items_df['item_category'].astype(str).str.len().gt(0)
        & comparable_items_df['item_category'].apply(lambda c: _category_matches(c, target_category))
        & comparable_items_df['price'].notna()
        & comparable_items_df['annual_qty'].notna()
        & (comparable_items_df['annual_qty'] > 0)
    ].copy()
    if candidates.empty:
        return None

    max_qty = candidates['annual_qty'].max()
    price_scores, volume_scores = [], []
    for _, row in candidates.iterrows():
        price_diff_pct = abs(float(row['price']) - target_price) / target_price if target_price else 1.0
        price_scores.append(max(0.0, 1.0 - min(1.0, price_diff_pct)))
        volume_scores.append(float(row['annual_qty']) / max_qty if max_qty else 0.0)

    candidates['_price_score'] = price_scores
    candidates['_volume_score'] = volume_scores
    candidates['_composite'] = price_weight * candidates['_price_score'] + volume_weight * candidates['_volume_score']

    best = candidates.sort_values('_composite', ascending=False).iloc[0]
    return {
        'name': best.get('item_name') or best.get('restaurant_name', 'Comparable item'),
        'restaurant_name': best.get('restaurant_name', ''),
        'category': best.get('item_category', ''),
        'price': float(best['price']),
        'annual_qty': float(best['annual_qty']),
        'composite_score': round(float(best['_composite']), 4),
        'match_note': (
            f"Best-ranked comparable item from the reference sales file (composite of price "
            f"competitiveness and sales volume, {price_weight:.0%}/{volume_weight:.0%} weighted) "
            f"among {len(candidates)} same-category candidate item(s)."
        ),
    }


# ---------------------------------------------------------------------------
# 1. CATEGORY VOLUME INDEX
# Real comparable-restaurant sales benchmark table -- average units-sold-
# per-menu-item by category, verified directly against the actual
# grizzlies_sales_data_CLEANED.csv (682 rows, 9 categories, ZCTA 38103):
# every value below matches df.groupby('FAMILY_GROUP_NAME')['STORE_QTY_SOLD']
# .mean() from that file exactly. (Earlier versions of this comment noted
# this table was reverse-engineered from the reference workbook's own
# documentation of the CSV, not the CSV itself -- that gap is now closed.)
# ---------------------------------------------------------------------------
CATEGORY_VOLUME_BENCHMARK = {
    "BURGER": 697.71, "BREAKFAST": 341.27, "APPETIZER": 258.2, "ENTREE": 200.28,
    "SAND / WRAP": 172.55, "SIDE / OTHER": 100.74, "SALAD": 75.14,
    "SOUP": 70.66, "BREAKFAST SIDE": 44.57,
}
_CATEGORY_VOLUME_MEAN = sum(CATEGORY_VOLUME_BENCHMARK.values()) / len(CATEGORY_VOLUME_BENCHMARK)

# creation_engine's CATEGORY_KEYWORDS labels (Wings, Burgers, Pizza, ...) map
# to this table's keys the same way output_row_builder.py already maps them
# to input_normalizer.CATEGORY_FC_BENCHMARK -- reuse that exact mapping so
# the two "which food-cost/volume bucket does this category fall in" answers
# never silently diverge.
from output_row_builder import CATEGORY_TO_FC_BENCHMARK_KEY as CATEGORY_TO_VOLUME_BENCHMARK_KEY


def category_volume_index(category: str) -> float:
    """Category Volume Index = this category's average units-sold-per-item
    (from the real comparable-sales benchmark table) / the mean across all
    9 categories in that same table. A relative popularity multiplier
    across categories, not an absolute unit count."""
    key = CATEGORY_TO_VOLUME_BENCHMARK_KEY.get(category)
    benchmark = CATEGORY_VOLUME_BENCHMARK.get(key)
    if benchmark is None:
        return 1.0  # neutral multiplier for a category with no benchmark match
    return round(benchmark / _CATEGORY_VOLUME_MEAN, 4)


# ---------------------------------------------------------------------------
# 2. CATEGORY DEMAND LEVEL -> CATEGORY MULTIPLIER
# Verified against the reference workbook exactly at High->1.05 and
# Medium->1.00 and Low->0.95; Very High->1.10 and Very Low->0.90 follow the
# same clean 0.05 step and were not directly observed in the sample but are
# the only pattern consistent with the three confirmed points.
# ---------------------------------------------------------------------------
CATEGORY_DEMAND_LEVEL_THRESHOLDS = (
    (2.00, "Very High", 1.10),
    (1.00, "High", 1.05),
    (0.60, "Medium", 1.00),
    (0.30, "Low", 0.95),
    (0.0, "Very Low", 0.90),
)


def category_demand_level(index: float):
    for threshold, label, multiplier in CATEGORY_DEMAND_LEVEL_THRESHOLDS:
        if index >= threshold:
            return label, multiplier
    return "Very Low", 0.90


# ---------------------------------------------------------------------------
# 3. MARKET DEMAND COMPOSITE INDEX -> MARKET DEMAND LEVEL -> DEMAND MULTIPLIER
# Formula and thresholds verified exactly against the reference workbook
# (reproduced its Composite Index to 11 decimal places: 1.01271944444444).
# National benchmarks below are the reference workbook's own stated
# neutral-comparison points.
# ---------------------------------------------------------------------------
NATIONAL_POP_GROWTH_BENCHMARK = 0.0            # neutral (0% growth = matches benchmark)
NATIONAL_RESTAURANT_DENSITY_BENCHMARK = 2.0     # per 1,000 residents
NATIONAL_LABOR_FORCE_PARTICIPATION_BENCHMARK = 0.63  # 63%

MARKET_DEMAND_LEVEL_THRESHOLDS = (
    (1.05, "Strong", 1.10),   # multiplier inferred symmetric to Category Multiplier's step;
    (0.95, "Moderate", 1.00),  # Moderate->1.00 is the one point verified against the reference workbook
    (0.0, "Weak", 0.90),       # inferred symmetric
)


def market_demand_composite(ctx: ZctaContext, population_growth_rate: float = None) -> float:
    """population_growth_rate: fraction (e.g. -0.1655 for -16.55%); if not
    supplied, falls back to ctx.population_growth_rate (None -> treated as
    0.0, i.e. exactly at the national benchmark -- stated as an assumption,
    not measured, when population_growth_rate is unavailable)."""
    growth_rate = population_growth_rate
    if growth_rate is None:
        growth_rate = ctx.population_growth_rate if ctx.population_growth_rate is not None else 0.0

    pop_growth_factor = 1 + (growth_rate - NATIONAL_POP_GROWTH_BENCHMARK)

    density = ctx.restaurant_density_per_1000()
    if density > 0:
        competition_favorability = min(1.3, NATIONAL_RESTAURANT_DENSITY_BENCHMARK / density)
    else:
        competition_favorability = 1.3  # no competitors found -> most favorable, capped same as any other ZCTA

    labor_force_factor = ctx.labor_force_participation_rate / 100.0 / NATIONAL_LABOR_FORCE_PARTICIPATION_BENCHMARK

    composite = 0.40 * pop_growth_factor + 0.35 * competition_favorability + 0.25 * labor_force_factor
    return composite


def market_demand_level_and_multiplier(composite_index: float):
    for threshold, label, multiplier in MARKET_DEMAND_LEVEL_THRESHOLDS:
        if composite_index >= threshold:
            return label, multiplier
    return "Weak", 0.90


# ---------------------------------------------------------------------------
# 4. BASE UNITS (MONTHLY)
# Primary source: real annual_qty from the optional comparable-restaurant
# file, for whichever comparable(s) were matched to this item (averaged
# across however many of the 1-2 matched comparables have usable qty data,
# then divided by 12 for a monthly figure). This is real, uploaded sales
# data for a named real restaurant -- the strongest evidence tier available
# in this pipeline, ahead of any modeled estimate.
#
# Fallback (only when no matched comparable has usable qty data): a
# transparent capture-rate model using the exact constants the reference
# workbook already documents (0.0005 capture rate, 22 weekday / 8 weekend
# days per month), scaled by this item's price tier's household share.
# Clearly labeled as an estimate in the returned source string -- never
# silently blended with the real-data path so a report reader can always
# tell which one produced a given number.
# ---------------------------------------------------------------------------
ASSUMED_CAPTURE_RATE = 0.0005
WEEKDAY_DAYS_PER_MONTH = 22
WEEKEND_DAYS_PER_MONTH = 8

TIER_SHARE_FIELD = {"Value": "family_pct", "Premium": "premium_pct", "Premium Edge": "premium_edge_pct"}


def compute_base_units_monthly(comparable_details: list, tier: str, ctx: ZctaContext,
                                best_item_match: dict = None):
    """comparable_details: the same list built in run_menu_creation.run()
    -- dicts with 'name'/'price'/'annual_qty', 'annual_qty' is None when
    the optional comparable file didn't have (or didn't match) that
    restaurant. Restaurant-level, averaged across up to 2 comparables.

    best_item_match: optional, from find_best_comparable_item() -- a
    SINGLE best-ranked item-level match (composite of price competitiveness
    and sales volume) from the reference sales file. When present, this
    takes priority over the restaurant-level average above: a specific,
    ranked comparable item is stronger evidence than an unranked average
    across whichever restaurants happened to be category-matched.

    Returns (base_units_monthly: float, source: str).
    """
    if best_item_match and best_item_match.get("annual_qty"):
        return round(best_item_match["annual_qty"] / 12.0, 2), (
            f"Best-matched comparable item from the reference sales file: "
            f"\u201c{best_item_match.get('name', 'item')}\u201d "
            f"(composite score {best_item_match.get('composite_score', 0):.3f} of price "
            f"competitiveness + sales volume). {best_item_match.get('match_note', '')}"
        )

    qtys = [d.get("annual_qty") for d in (comparable_details or []) if d.get("annual_qty") not in (None, "")]
    if qtys:
        avg_annual = sum(qtys) / len(qtys)
        return round(avg_annual / 12.0, 2), (
            f"Real comparable-restaurant sales data ({len(qtys)} matched comparable(s) "
            f"from the uploaded comparable-data file, averaged, /12 for a monthly figure)."
        )

    # Fallback: no usable comparable quantity data for this item.
    weekday_pop = ctx.in_commuting_workers + ctx.resident_employed_workers  # daytime presence estimate
    weekend_pop = ctx.total_population
    person_days = weekday_pop * WEEKDAY_DAYS_PER_MONTH + weekend_pop * WEEKEND_DAYS_PER_MONTH

    tier_field = TIER_SHARE_FIELD.get(tier, "family_pct")
    tier_pct = getattr(ctx, tier_field, 0.0) / 100.0

    base_units = ASSUMED_CAPTURE_RATE * person_days * tier_pct
    return round(base_units, 2), (
        "Reasoned estimate (no comparable-restaurant sales data matched for this item -- "
        f"capture-rate model: {ASSUMED_CAPTURE_RATE} assumed capture rate x monthly person-day "
        f"exposure x {tier} tier's household share)."
    )


# ---------------------------------------------------------------------------
# 5. BASE PROJECTED UNITS -> PERIOD FORECAST
# Verified exactly against the reference workbook.
# ---------------------------------------------------------------------------
PERIOD_FACTORS = {
    "6m": 5.4,       # Months 1-6 (ramping)
    "next6m": 6.0,   # Months 7-12 (fully ramped)
    "next9m": 9.0,   # Months 13-21 (fully ramped)
}


def base_projected_units(base_units_monthly: float, demand_multiplier: float, category_multiplier: float) -> float:
    return round(base_units_monthly * demand_multiplier * category_multiplier, 2)


def period_forecast(base_proj_units: float, price: float) -> dict:
    out = {}
    for period, factor in PERIOD_FACTORS.items():
        units = round(base_proj_units * factor, 2)
        revenue = round(units * price, 2)
        out[f"{period}_units"] = units
        out[f"{period}_revenue"] = revenue
    return out


# ---------------------------------------------------------------------------
# 6. LUNCH/DINNER + WEEKDAY/WEEKEND OCCASION SPLITS
# Tier-based lunch share table and day-counts, verbatim from the reference
# workbook's own "documented judgment call" section -- these were labeled
# an assumption there too, not measured data, so implementing them as a
# fixed table here carries the same evidentiary status as the reference.
# ---------------------------------------------------------------------------
LUNCH_SHARE_BY_TIER = {"Value": 0.55, "Premium": 0.25, "Premium Edge": 0.15}


def lunch_dinner_split(base_proj_units: float, price: float, tier: str,
                        lunch_price_mult: float = 0.98, dinner_price_mult: float = 1.00):
    lunch_share = LUNCH_SHARE_BY_TIER.get(tier, 0.55)
    dinner_share = round(1 - lunch_share, 4)

    lunch_units = round(base_proj_units * lunch_share, 2)
    dinner_units = round(base_proj_units * dinner_share, 2)
    lunch_price = round(price * lunch_price_mult, 2)
    dinner_price = round(price * dinner_price_mult, 2)

    return {
        "lunch_share": lunch_share, "lunch_price": lunch_price, "lunch_units": lunch_units,
        "lunch_revenue": round(lunch_units * lunch_price, 2), "lunch_price_mult": lunch_price_mult,
        "dinner_share": dinner_share, "dinner_price": dinner_price, "dinner_units": dinner_units,
        "dinner_revenue": round(dinner_units * dinner_price, 2), "dinner_price_mult": dinner_price_mult,
    }


# Weekday/weekend UNIT split, by tier -- a documented policy table, same
# status and pattern as LUNCH_SHARE_BY_TIER above, NOT derived from
# crowd_mix_split()'s weekday/weekend percentages. Those percentages
# represent each tier's share of that tier's OWN weekday/weekend customer
# base -- useful for "Weekday Menu Role"/"Weekend Menu Role" narrative
# text, but their ratio to each other is mathematically identical for
# every tier by construction (the commuter lift factor is ZCTA-wide, not
# tier-specific, so it cancels out of the ratio regardless of which tier's
# percentage you start from). An earlier version of this function reused
# that ratio for the unit split and silently produced the same 52.38/47.62
# split for every tier, which is wrong -- Value (routine, everyday) items
# should skew more weekday; Premium Edge (occasion) items should skew more
# weekend. This table encodes that difference explicitly instead.
WEEKDAY_SHARE_BY_TIER = {"Value": 0.60, "Premium": 0.45, "Premium Edge": 0.30}


def weekday_weekend_split(base_proj_units: float, price: float, tier: str, ctx: ZctaContext,
                           weekday_price_mult: float = 1.0, weekend_price_mult: float = 1.0):
    """Weekday/weekend unit split for revenue-forecast purposes, using an
    explicit tier-based policy table (see WEEKDAY_SHARE_BY_TIER) rather
    than crowd_mix_split()'s ratio, which cannot structurally vary by tier
    (see module comment above)."""
    weekday_share = WEEKDAY_SHARE_BY_TIER.get(tier, 0.60)
    weekend_share = round(1 - weekday_share, 4)

    weekday_units = round(base_proj_units * weekday_share, 2)
    weekend_units = round(base_proj_units * weekend_share, 2)
    weekday_price = round(price * weekday_price_mult, 2)
    weekend_price = round(price * weekend_price_mult, 2)

    return {
        "weekday_share": weekday_share, "weekday_price": weekday_price, "weekday_units": weekday_units,
        "weekday_revenue": round(weekday_units * weekday_price, 2), "weekday_price_mult": weekday_price_mult,
        "weekend_share": weekend_share, "weekend_price": weekend_price, "weekend_units": weekend_units,
        "weekend_revenue": round(weekend_units * weekend_price, 2), "weekend_price_mult": weekend_price_mult,
    }


# ---------------------------------------------------------------------------
# 7. POPULARITY SCORE / RANK
# Verified exactly against the reference workbook (Popularity Score = 4.7396
# = 4 confidence x 1.1849 category volume index).
# ---------------------------------------------------------------------------
def popularity_score(confidence_score: int, cat_volume_index: float) -> float:
    return round(confidence_score * cat_volume_index, 4)


def popularity_ranks(scores: list) -> list:
    """scores: list of popularity_score() values in item order.
    Returns parallel list of 1-based ranks, 1 = most popular (highest score)."""
    order = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)
    ranks = [0] * len(scores)
    for rank, idx in enumerate(order, start=1):
        ranks[idx] = rank
    return ranks


# ---------------------------------------------------------------------------
# 8. TOP-LEVEL: build the full forecast block for one item
# ---------------------------------------------------------------------------
def build_revenue_forecast_row(category: str, tier: str, price: float, confidence_score: int,
                                comparable_details: list, ctx: ZctaContext,
                                best_item_match: dict = None) -> dict:
    cat_index = category_volume_index(category)
    cat_level, cat_mult = category_demand_level(cat_index)

    composite = market_demand_composite(ctx)
    demand_level, demand_mult = market_demand_level_and_multiplier(composite)

    base_units, base_units_source = compute_base_units_monthly(comparable_details, tier, ctx, best_item_match)
    proj_units = base_projected_units(base_units, demand_mult, cat_mult)
    periods = period_forecast(proj_units, price)

    ld = lunch_dinner_split(proj_units, price, tier)
    wdwe = weekday_weekend_split(proj_units, price, tier, ctx)

    pop_score = popularity_score(confidence_score, cat_index)

    return {
        "Comparable Sales Category (for Volume Index)": category,
        "Category Volume Index (real comparable-sales data)": cat_index,
        "Category Demand Level": cat_level,
        "Category Multiplier": cat_mult,
        "Popularity Score (Confidence x Category Volume Index)": pop_score,
        "Market Demand Composite Index (computed)": round(composite, 6),
        "Market Demand Level (computed)": demand_level,
        "Demand Multiplier (ZIP-wide, from Market Demand Level)": demand_mult,
        "Base Units (Monthly) -- category/market demand methodology, no multipliers applied": base_units,
        "Base Units Source": base_units_source,
        "Base Projected Units (Monthly) = Base Units x Demand Multiplier x Category Multiplier": proj_units,
        "Lunch Unit Share (%)": ld["lunch_share"], "Lunch Occasion Price ($)": ld["lunch_price"],
        "Lunch Price Multiplier": ld["lunch_price_mult"],
        "Lunch Estimated Units (Monthly)": ld["lunch_units"], "Lunch Estimated Revenue (Monthly $)": ld["lunch_revenue"],
        "Dinner Unit Share (%)": ld["dinner_share"], "Dinner Occasion Price ($)": ld["dinner_price"],
        "Dinner Price Multiplier": ld["dinner_price_mult"],
        "Dinner Estimated Units (Monthly)": ld["dinner_units"], "Dinner Estimated Revenue (Monthly $)": ld["dinner_revenue"],
        "Weekday Unit Share (%)": wdwe["weekday_share"], "Weekday Occasion Price ($)": wdwe["weekday_price"],
        "Weekday Price Multiplier": wdwe["weekday_price_mult"],
        "Weekday Estimated Units (Monthly)": wdwe["weekday_units"], "Weekday Estimated Revenue (Monthly $)": wdwe["weekday_revenue"],
        "Weekend Unit Share (%)": wdwe["weekend_share"], "Weekend Occasion Price ($)": wdwe["weekend_price"],
        "Weekend Price Multiplier": wdwe["weekend_price_mult"],
        "Weekend Estimated Units (Monthly)": wdwe["weekend_units"], "Weekend Estimated Revenue (Monthly $)": wdwe["weekend_revenue"],
        # This item's own steady-state monthly revenue -- the "Projected
        # Revenue" headline figure for the per-item pop-up. Always labeled
        # Estimated (every input feeding it -- base units, demand
        # multiplier, category multiplier -- is itself a computed/derived
        # figure, never a directly-observed sale for a menu item that
        # doesn't exist yet).
        "Estimated Steady-State Monthly Revenue ($)": round(proj_units * price, 2),
        "6-Month Units (Months 1-6)": periods["6m_units"], "Estimated 6-Month Revenue ($)": periods["6m_revenue"],
        "Next 6-Month Units (Months 7-12)": periods["next6m_units"], "Estimated Next 6-Month Revenue ($)": periods["next6m_revenue"],
        "Next 9-Month Units (Months 13-21)": periods["next9m_units"], "Estimated Next 9-Month Revenue ($)": periods["next9m_revenue"],
    }